### PR TITLE
Enhancement/performance

### PR DESCRIPTION
**Pull request by whatisinternet**
# What it does:
- Fixes performance issues brought up with #18 and #25 

# Why it does it:
- Performance was lower than the equal ruby implementation

# Related issues:
- #18, #25

## Benchmarks:
```shell
test cases::camelcase::tests::bench_camel0                      ... bench:         139 ns/iter (+/- 40)
test cases::camelcase::tests::bench_camel1                      ... bench:         138 ns/iter (+/- 31)
test cases::camelcase::tests::bench_camel2                      ... bench:         138 ns/iter (+/- 41)
test cases::camelcase::tests::bench_is_camel                    ... bench:         184 ns/iter (+/- 90)
test cases::classcase::tests::bench_class_case                  ... bench:       2,383 ns/iter (+/- 557)
test cases::classcase::tests::bench_class_from_snake            ... bench:       2,393 ns/iter (+/- 1,120)
test cases::classcase::tests::bench_is_class                    ... bench:       2,443 ns/iter (+/- 1,060)
test cases::kebabcase::tests::bench_is_kebab                    ... bench:         182 ns/iter (+/- 60)
test cases::kebabcase::tests::bench_kebab                       ... bench:         161 ns/iter (+/- 98)
test cases::kebabcase::tests::bench_kebab_from_snake            ... bench:         264 ns/iter (+/- 144)
test cases::lowercase::tests::bench_is_lower                    ... bench:         358 ns/iter (+/- 154)
test cases::lowercase::tests::bench_lower                       ... bench:         347 ns/iter (+/- 220)
test cases::screamingsnakecase::tests::bench_is_screaming_snake ... bench:         194 ns/iter (+/- 35)
test cases::screamingsnakecase::tests::bench_screaming_snake    ... bench:         173 ns/iter (+/- 97)
test cases::sentencecase::tests::bench_is_sentence              ... bench:         377 ns/iter (+/- 83)
test cases::sentencecase::tests::bench_sentence                 ... bench:         337 ns/iter (+/- 155)
test cases::sentencecase::tests::bench_sentence_from_snake      ... bench:         370 ns/iter (+/- 176)
test cases::snakecase::tests::bench_is_snake                    ... bench:         191 ns/iter (+/- 98)
test cases::snakecase::tests::bench_snake_from_camel            ... bench:         156 ns/iter (+/- 25)
test cases::snakecase::tests::bench_snake_from_snake            ... bench:         289 ns/iter (+/- 136)
test cases::snakecase::tests::bench_snake_from_title            ... bench:         157 ns/iter (+/- 68)
test cases::tablecase::tests::bench_is_table_case               ... bench:       2,253 ns/iter (+/- 978)
test cases::tablecase::tests::bench_table_case                  ... bench:       2,227 ns/iter (+/- 704)
test cases::titlecase::tests::bench_is_title                    ... bench:         787 ns/iter (+/- 362)
test cases::titlecase::tests::bench_title                       ... bench:         826 ns/iter (+/- 317)
test cases::titlecase::tests::bench_title_from_snake            ... bench:         747 ns/iter (+/- 230)
test cases::uppercase::tests::bench_is_upper                    ... bench:         347 ns/iter (+/- 111)
test cases::uppercase::tests::bench_upper                       ... bench:         328 ns/iter (+/- 42)
```

## OLD Benchmarks:
```shell
test cases::camelcase::tests::bench_camel                                         ... bench:       1,825 ns/iter (+/- 346)
test cases::camelcase::tests::bench_camel_from_sname                              ... bench:       1,223 ns/iter (+/- 289)
test cases::camelcase::tests::bench_is_camel                                      ... bench:      49,416 ns/iter (+/- 593)
test cases::classcase::tests::bench_class_case                                    ... bench: 160,985,376 ns/iter (+/- 5,173,751)
test cases::classcase::tests::bench_class_from_snake                              ... bench: 161,533,425 ns/iter (+/- 4,167,305)
test cases::classcase::tests::bench_is_class                                      ... bench: 161,352,118 ns/iter (+/- 3,793,478)
test cases::kebabcase::tests::bench_is_kebab                                      ... bench:         793 ns/iter (+/- 400)
test cases::kebabcase::tests::bench_kebab                                         ... bench:         752 ns/iter (+/- 310)
test cases::kebabcase::tests::bench_kebab_from_snake                              ... bench:         210 ns/iter (+/- 32)
test cases::lowercase::tests::bench_is_lower                                      ... bench:         340 ns/iter (+/- 86)
test cases::lowercase::tests::bench_lower                                         ... bench:         306 ns/iter (+/- 173)
test cases::screamingsnakecase::tests::bench_is_screaming_snake                   ... bench:         635 ns/iter (+/- 210)
test cases::screamingsnakecase::tests::bench_screaming_snake                      ... bench:         610 ns/iter (+/- 87)
test cases::screamingsnakecase::tests::bench_screaming_snake_from_camel           ... bench:         961 ns/iter (+/- 579)
test cases::screamingsnakecase::tests::bench_screaming_snake_from_class           ... bench:         894 ns/iter (+/- 352)
test cases::screamingsnakecase::tests::bench_screaming_snake_from_kebab           ... bench:         877 ns/iter (+/- 571)
test cases::screamingsnakecase::tests::bench_screaming_snake_from_screaming_snake ... bench:         584 ns/iter (+/- 304)
test cases::screamingsnakecase::tests::bench_screaming_snake_from_sentence        ... bench:       1,123 ns/iter (+/- 630)
test cases::screamingsnakecase::tests::bench_screaming_snake_from_upper_kebab     ... bench:         914 ns/iter (+/- 435)
test cases::sentencecase::tests::bench_is_sentence                                ... bench:       2,714 ns/iter (+/- 796)
test cases::sentencecase::tests::bench_sentence                                   ... bench:       2,678 ns/iter (+/- 1,357)
test cases::sentencecase::tests::bench_sentence_from_snake                        ... bench:       2,100 ns/iter (+/- 1,046)
test cases::snakecase::tests::bench_is_snake                                      ... bench:         626 ns/iter (+/- 191)
test cases::snakecase::tests::bench_snake                                         ... bench:         581 ns/iter (+/- 298)
test cases::snakecase::tests::bench_snake_from_camel                              ... bench:         882 ns/iter (+/- 328)
test cases::snakecase::tests::bench_snake_from_class                              ... bench:         883 ns/iter (+/- 193)
test cases::snakecase::tests::bench_snake_from_kebab                              ... bench:         922 ns/iter (+/- 360)
test cases::snakecase::tests::bench_snake_from_sentence                           ... bench:       1,209 ns/iter (+/- 539)
test cases::snakecase::tests::bench_snake_from_snake                              ... bench:         637 ns/iter (+/- 386)
test cases::snakecase::tests::bench_snake_from_upper_kebab                        ... bench:         876 ns/iter (+/- 488)
test cases::tablecase::tests::bench_is_table_case                                 ... bench:       5,784 ns/iter (+/- 1,129)
test cases::tablecase::tests::bench_table_case                                    ... bench:       5,754 ns/iter (+/- 1,460)
test cases::titlecase::tests::bench_is_title                                      ... bench:       2,847 ns/iter (+/- 1,553)
test cases::titlecase::tests::bench_title                                         ... bench:       2,799 ns/iter (+/- 1,309)
test cases::titlecase::tests::bench_title_from_snake                              ... bench:       2,202 ns/iter (+/- 697)
test cases::uppercase::tests::bench_is_upper                                      ... bench:         357 ns/iter (+/- 55)
test cases::uppercase::tests::bench_upper                                         ... bench:         311 ns/iter (+/- 135)

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
is this faster than the implementation done by @calebmer https://github.com/whatisinternet/inflector/issues/18#issuecomment-213879759
?

**Comment by whatisinternet** [comment]
@NullVoxPopuli I only benched against camel case on his crate but here are the results:

```shell
// Inflections
test case::tests::bench_camel0   ... bench:         424 ns/iter (+/- 89)
test case::tests::bench_camel1   ... bench:         441 ns/iter (+/- 134)
test case::tests::bench_camel2   ... bench:         412 ns/iter (+/- 167)
test case::tests::bench_is_camel ... bench:         445 ns/iter (+/- 198)
```

```shell
// Inflector
test cases::camelcase::tests::bench_camel0                      ... bench:         139 ns/iter (+/- 40)
test cases::camelcase::tests::bench_camel1                      ... bench:         138 ns/iter (+/- 31)
test cases::camelcase::tests::bench_camel2                      ... bench:         138 ns/iter (+/- 41)
test cases::camelcase::tests::bench_is_camel                    ... bench:         184 ns/iter (+/- 90)
```

looks like Inflector is faster now 👍. I'm happy to bench the rest of his crate tomorrow. If you're looking at using `Inflector` in your project I'd be interested in the benchmarks on your side too.

**Comment by whatisinternet** [comment]
# Complete bench results from [inflections](https://github.com/calebmer/inflections):

**Note**: Inflections is missing some of the features of inflector thus only the features supported are benchmarked)

**Note**: All benchmarks were run using `rustc 1.13.0-nightly (4f9812a59 2016-09-21)`

```shell
test case::tests::bench_camel0              ... bench:         425 ns/iter (+/- 91)
test case::tests::bench_camel1              ... bench:         434 ns/iter (+/- 169)
test case::tests::bench_camel2              ... bench:         403 ns/iter (+/- 184)
test case::tests::bench_is_camel            ... bench:         464 ns/iter (+/- 79)
test case::tests::bench_is_kebab            ... bench:         336 ns/iter (+/- 145)
test case::tests::bench_is_lower            ... bench:         284 ns/iter (+/- 102)
test case::tests::bench_is_screaming_snake  ... bench:         470 ns/iter (+/- 612)
test case::tests::bench_is_sentence         ... bench:         343 ns/iter (+/- 89)
test case::tests::bench_is_snake            ... bench:         347 ns/iter (+/- 178)
test case::tests::bench_is_title            ... bench:         425 ns/iter (+/- 113)
test case::tests::bench_is_upper            ... bench:         302 ns/iter (+/- 50)
test case::tests::bench_kebab               ... bench:         317 ns/iter (+/- 94)
test case::tests::bench_kebab_from_snake    ... bench:         660 ns/iter (+/- 224)
test case::tests::bench_lower               ... bench:         287 ns/iter (+/- 127)
test case::tests::bench_screaming_snake     ... bench:         315 ns/iter (+/- 106)
test case::tests::bench_sentence            ... bench:         333 ns/iter (+/- 130)
test case::tests::bench_sentence_from_snake ... bench:         334 ns/iter (+/- 74)
test case::tests::bench_snake_from_camel    ... bench:         319 ns/iter (+/- 110)
test case::tests::bench_snake_from_snake    ... bench:         712 ns/iter (+/- 300)
test case::tests::bench_snake_from_title    ... bench:         333 ns/iter (+/- 232)
test case::tests::bench_title               ... bench:         438 ns/iter (+/- 199)
test case::tests::bench_title_from_snake    ... bench:         465 ns/iter (+/- 155)
test case::tests::bench_upper               ... bench:         306 ns/iter (+/- 47)
```

# Benchmark code used on `inflections`:
**Note**: Run on `master` as of posting
```rust
#[cfg(test)]
mod tests {
    extern crate test;
    use self::test::Bencher;

    #[bench]
    fn bench_camel0(b: &mut Bencher) {
        b.iter(|| super::to_camel_case("Foo bar"));
    }

    #[bench]
    fn bench_camel1(b: &mut Bencher) {
        b.iter(|| super::to_camel_case("foo_bar"));
    }

    #[bench]
    fn bench_camel2(b: &mut Bencher) {
        b.iter(|| super::to_camel_case("fooBar"));
    }

    #[bench]
    fn bench_is_camel(b: &mut Bencher) {
        b.iter(|| super::is_camel_case("Foo bar"));
    }
    #[bench]
    fn bench_kebab(b: &mut Bencher) {
        b.iter(|| super::to_kebab_case("Foo bar"));
    }

    #[bench]
    fn bench_is_kebab(b: &mut Bencher) {
        b.iter(|| super::is_kebab_case("Foo bar"));
    }

    #[bench]
    fn bench_kebab_from_snake(b: &mut Bencher) {
        b.iter(|| super::to_kebab_case("test_test_test"));
    }
    #[bench]
    fn bench_lower(b: &mut Bencher) {
        b.iter(|| super::to_lower_case("Foo BAR"));
    }

    #[bench]
    fn bench_is_lower(b: &mut Bencher) {
        b.iter(|| super::is_lower_case("Foo bar"));
    }
    #[bench]
    fn bench_screaming_snake(b: &mut Bencher) {
        b.iter(|| super::to_constant_case("Foo bar"));
    }

    #[bench]
    fn bench_is_screaming_snake(b: &mut Bencher) {
        b.iter(|| super::is_constant_case("Foo bar"));
    }
    #[bench]
    fn bench_sentence(b: &mut Bencher) {
        b.iter(|| super::to_sentence_case("Foo BAR"));
    }

    #[bench]
    fn bench_is_sentence(b: &mut Bencher) {
        b.iter(|| super::is_sentence_case("Foo bar"));
    }

    #[bench]
    fn bench_sentence_from_snake(b: &mut Bencher) {
        b.iter(|| super::to_sentence_case("foo_bar"));
    }
    #[bench]
    fn bench_snake_from_title(b: &mut Bencher) {
        b.iter(|| super::to_snake_case("Foo bar"));
    }

    #[bench]
    fn bench_snake_from_camel(b: &mut Bencher) {
        b.iter(|| super::to_snake_case("fooBar"));
    }

    #[bench]
    fn bench_snake_from_snake(b: &mut Bencher) {
        b.iter(|| super::to_snake_case("foo_bar_bar_bar"));
    }

    #[bench]
    fn bench_is_snake(b: &mut Bencher) {
        b.iter(|| super::is_snake_case("Foo bar"));
    }
    #[bench]
    fn bench_title(b: &mut Bencher) {
        b.iter(|| super::to_title_case("Foo BAR"));
    }

    #[bench]
    fn bench_is_title(b: &mut Bencher) {
        b.iter(|| super::is_title_case("Foo bar"));
    }

    #[bench]
    fn bench_title_from_snake(b: &mut Bencher) {
        b.iter(|| super::to_title_case("foo_bar"));
    }
    #[bench]
    fn bench_upper(b: &mut Bencher) {
        b.iter(|| super::to_upper_case("Foo BAR"));
    }

    #[bench]
    fn bench_is_upper(b: &mut Bencher) {
        b.iter(|| super::is_upper_case("Foo bar"));
    }
}

```

**Comment by NullVoxPopuli** [comment]
With your updated package (0.3.3)

```
$ ruby benchmark.rb 

Comparison:
Memoized Ruby: camel:   178279.5 i/s
         Rust: camel:   108284.3 i/s - 1.65x  slower
         Ruby: camel:     9931.5 i/s - 17.95x  slower


Comparison:
   Rust: camel_lower:   229129.2 i/s
Memoized Ruby: camel_lower:   155403.6 i/s - same-ish: difference falls within error
   Ruby: camel_lower:    10549.2 i/s - 21.72x  slower


Comparison:
          Rust: dash:   356658.8 i/s
 Memoized Ruby: dash:   162317.0 i/s - 2.20x  slower
          Ruby: dash:    26288.0 i/s - 13.57x  slower


Comparison:
     Ruby: unaltered:  6792150.5 i/s
Memoized Ruby: unaltered:  6542423.9 i/s - same-ish: difference falls within error
     Rust: unaltered:  2178876.4 i/s - 3.12x  slower


Comparison:
    Rust: underscore:   410279.8 i/s
Memoized Ruby: underscore:   209977.8 i/s - 1.95x  slower
    Ruby: underscore:   178985.0 i/s - 2.29x  slower
```

with the other package (https://github.com/calebmer/inflections)

```

Comparison:
         Rust: camel:   262327.0 i/s
Memoized Ruby: camel:   169865.6 i/s - 1.54x  slower
         Ruby: camel:    13637.7 i/s - 19.24x  slower


Comparison:
   Rust: camel_lower:   267782.1 i/s
Memoized Ruby: camel_lower:   179085.1 i/s - 1.50x  slower
   Ruby: camel_lower:    11147.1 i/s - 24.02x  slower


Comparison:
          Rust: dash:   271227.1 i/s
 Memoized Ruby: dash:   177079.4 i/s - 1.53x  slower
          Ruby: dash:    18680.9 i/s - 14.52x  slower


Comparison:
Memoized Ruby: unaltered:  6893719.6 i/s
     Ruby: unaltered:  4976229.6 i/s - 1.39x  slower
     Rust: unaltered:  2137102.1 i/s - 3.23x  slower


Comparison:
    Rust: underscore:   311421.1 i/s
Memoized Ruby: underscore:   214460.2 i/s - 1.45x  slower
    Ruby: underscore:   176893.2 i/s - 1.76x  slower


```

**Comment by whatisinternet** [comment]
The major issue looks like class case where I do an extra singularization step (which is still only a little slower). I'll think about or would be willing to accept a PR for Pascal case (since there is a use case for it)  which should bring the speed equal or better to @calebmer's project in all of your benchmarks.

**Pull request merged**
