### PR TITLE
Train-Case

### PR DESCRIPTION
**Pull request by stpettersens**
# What it does:

Train-Case: Converts strings to Train-Case.
(Like kebab-case but each word is also capitalized).

# Why it does it:

I needed Train-Case in a program and rather than roll out 
my own library wanted to contribute to this existing
inflection library.

# Related issues:

None.

### CODE REVIEW

**Comment by whatisinternet** [comment]
Hey! Thanks for the PR! :+1:. I haven't had a chance to look at it yet but will soon :smile:. Could you run the benchmarks for me and post the results? You'll need to be on nightly Rust then run `cargo bench --freatures=unstable`

**Comment by whatisinternet** [comment]
Benchmarks feel a little slow. I'll have a look at the code and see if it can be made faster. :smiley: Performance for this should be in the same area as camel case etc (140ns/iter).

```shell
test cases::traincase::tests::bench_is_train                    ... bench:         780 ns/iter (+/- 152)
test cases::traincase::tests::bench_train                       ... bench:         745 ns/iter (+/- 236)
test cases::traincase::tests::bench_train_from_snake            ... bench:       1,120 ns/iter (+/- 589)
```

**Comment by stpettersens** [comment]
No. It's okay if modified Pascal Case beats it. I'm not really good at getting high performance Rust code. Still fairly new to it. Happy to have Train_Case, so thanks for improving it.

**Comment by stpettersens** [comment]
Made some tweaks and I got these benchmarks on Travis:

```
test cases::traincase::tests::bench_is_train                    ... bench:         183 ns/iter (+/- 2)
test cases::traincase::tests::bench_train                       ... bench:         167 ns/iter (+/- 3)
test cases::traincase::tests::bench_train_from_snake            ... bench:         261 ns/iter (+/- 5)
```

Not quite as good as yours. I think its almost there though, you can override with your implementation. It's based on Pascal Case code (as suggested), so I think you probably have something similar already.

**Comment by whatisinternet** [comment]
This is what mine looked like. Pretty minor change from what you got to so feel free to make make the change and I'll merge. :tada: 🍾 

```rust
pub fn to_train_case(non_train_case_string: String) -> String {
    let mut new_word: bool = true;
    let mut first_word: bool = true;
    let mut last_char: char = ' ';
    non_train_case_string
        .chars()
        .fold("".to_string(), |mut result, character|
            if character == '-' || character == '_' || character == ' ' {
                new_word = true;
                result
            } else if character.is_numeric() {
                new_word = true;
                result.push(character);
                result
            } else if new_word || (
                (last_char.is_lowercase() && character.is_uppercase()) &&
                (last_char != ' ')
                ){
                new_word = false;
                if !first_word {
                    result.push('-');
                }
                first_word = false;
                result.push(character.to_ascii_uppercase());
                result
            } else {
                last_char = character;
                result.push(character.to_ascii_lowercase());
                result
            }
        )
}
```

**Comment by stpettersens** [comment]
Okay. I made those changes. I guess the overhead is in trimming and then converting back to owned string. Either way, the bool approach is tidier. :)

**Pull request merged**
