### PR TITLE
Feature/&str

### LINKED ISSUE #47: Conversions should not consume String
Looks like most (all?) conversions create a new String, which means it should be sufficient for them to accept `&str` and not a `String`.

This way it would be possible to convert borrowed strings without cloning them (which is expensive due to extra temporary heap allocation and copying data).

### PR DESCRIPTION
**Pull request by whatisinternet**
# What it does:
- Changes API to act on `&str` by default

# Why it does it:
- Most of the conversions can be completed by acting on `&str`. This leads to a significant performance improvement over acting on `String` types directly.

# Related issues:
- Closes #47 

# Benchmarks:
```shell
test cases::camelcase::tests::bench_camel0                      ... bench:         132 ns/iter (+/- 15)
test cases::camelcase::tests::bench_camel1                      ... bench:         130 ns/iter (+/- 69)
test cases::camelcase::tests::bench_camel2                      ... bench:         133 ns/iter (+/- 21)
test cases::camelcase::tests::bench_is_camel                    ... bench:         127 ns/iter (+/- 21)
test cases::classcase::tests::bench_class_case                  ... bench:       2,605 ns/iter (+/- 1,422)
test cases::classcase::tests::bench_class_from_snake            ... bench:       2,474 ns/iter (+/- 1,400)
test cases::classcase::tests::bench_is_class                    ... bench:       2,447 ns/iter (+/- 279)
test cases::kebabcase::tests::bench_is_kebab                    ... bench:         151 ns/iter (+/- 29)
test cases::kebabcase::tests::bench_kebab                       ... bench:         156 ns/iter (+/- 25)
test cases::kebabcase::tests::bench_kebab_from_snake            ... bench:         254 ns/iter (+/- 54)
test cases::pascalcase::tests::bench_is_pascal                  ... bench:         129 ns/iter (+/- 17)
test cases::pascalcase::tests::bench_pascal0                    ... bench:         137 ns/iter (+/- 13)
test cases::pascalcase::tests::bench_pascal1                    ... bench:         135 ns/iter (+/- 50)
test cases::pascalcase::tests::bench_pascal2                    ... bench:         130 ns/iter (+/- 64)
test cases::screamingsnakecase::tests::bench_is_screaming_snake ... bench:         172 ns/iter (+/- 34)
test cases::screamingsnakecase::tests::bench_screaming_snake    ... bench:         177 ns/iter (+/- 21)
test cases::sentencecase::tests::bench_is_sentence              ... bench:         135 ns/iter (+/- 37)
test cases::sentencecase::tests::bench_sentence                 ... bench:         175 ns/iter (+/- 92)
test cases::sentencecase::tests::bench_sentence_from_snake      ... bench:         132 ns/iter (+/- 24)
test cases::snakecase::tests::bench_is_snake                    ... bench:         153 ns/iter (+/- 32)
test cases::snakecase::tests::bench_snake_from_camel            ... bench:         140 ns/iter (+/- 72)
test cases::snakecase::tests::bench_snake_from_snake            ... bench:         260 ns/iter (+/- 75)
test cases::snakecase::tests::bench_snake_from_title            ... bench:         149 ns/iter (+/- 72)
test cases::tablecase::tests::bench_is_table_case               ... bench:       2,453 ns/iter (+/- 401)
test cases::tablecase::tests::bench_table_case                  ... bench:       2,456 ns/iter (+/- 205)
test cases::titlecase::tests::bench_is_title                    ... bench:         133 ns/iter (+/- 59)
test cases::titlecase::tests::bench_title                       ... bench:         184 ns/iter (+/- 71)
test cases::titlecase::tests::bench_title_from_snake            ... bench:         133 ns/iter (+/- 40)
test cases::traincase::tests::bench_is_train                    ... bench:         143 ns/iter (+/- 86)
test cases::traincase::tests::bench_train                       ... bench:         129 ns/iter (+/- 25)
test cases::traincase::tests::bench_train_from_snake            ... bench:         246 ns/iter (+/- 125)
test tests::benchmark_str_deconstantize                         ... bench:       2,580 ns/iter (+/- 1,151)
test tests::benchmark_str_demodulize                            ... bench:       2,587 ns/iter (+/- 1,497)
test tests::benchmark_str_deordinalize                          ... bench:         125 ns/iter (+/- 24)
test tests::benchmark_str_is_camel                              ... bench:         133 ns/iter (+/- 19)
test tests::benchmark_str_is_class                              ... bench:       2,350 ns/iter (+/- 656)
test tests::benchmark_str_is_foreign_key                        ... bench:         228 ns/iter (+/- 57)
test tests::benchmark_str_is_kebab                              ... bench:         159 ns/iter (+/- 62)
test tests::benchmark_str_is_screaming_snake                    ... bench:         162 ns/iter (+/- 37)
test tests::benchmark_str_is_sentence                           ... bench:         135 ns/iter (+/- 44)
test tests::benchmark_str_is_snake                              ... bench:         152 ns/iter (+/- 21)
test tests::benchmark_str_is_table                              ... bench:       2,918 ns/iter (+/- 426)
test tests::benchmark_str_is_title                              ... bench:         133 ns/iter (+/- 45)
test tests::benchmark_str_is_train                              ... bench:         137 ns/iter (+/- 77)
test tests::benchmark_str_ordinalize                            ... bench:         129 ns/iter (+/- 25)
test tests::benchmark_str_pluralize                             ... bench:       2,282 ns/iter (+/- 577)
test tests::benchmark_str_singular                              ... bench:       2,690 ns/iter (+/- 568)
test tests::benchmark_str_to_camel                              ... bench:         127 ns/iter (+/- 33)
test tests::benchmark_str_to_class                              ... bench:       2,346 ns/iter (+/- 756)
test tests::benchmark_str_to_foreign_key                        ... bench:         435 ns/iter (+/- 2)
test tests::benchmark_str_to_kebab                              ... bench:         137 ns/iter (+/- 52)
test tests::benchmark_str_to_screaming_snake                    ... bench:         157 ns/iter (+/- 51)
test tests::benchmark_str_to_sentence                           ... bench:         138 ns/iter (+/- 3)
test tests::benchmark_str_to_snake                              ... bench:         137 ns/iter (+/- 33)
test tests::benchmark_str_to_table                              ... bench:       2,470 ns/iter (+/- 1,092)
test tests::benchmark_str_to_title                              ... bench:         139 ns/iter (+/- 14)
test tests::benchmark_str_to_train                              ... bench:         132 ns/iter (+/- 31)
test tests::benchmark_string_deconstantize                      ... bench:       2,610 ns/iter (+/- 1,451)
test tests::benchmark_string_demodulize                         ... bench:       2,767 ns/iter (+/- 2,864)
test tests::benchmark_string_deordinalize                       ... bench:         149 ns/iter (+/- 48)
test tests::benchmark_string_is_camel                           ... bench:         145 ns/iter (+/- 26)
test tests::benchmark_string_is_class                           ... bench:       2,380 ns/iter (+/- 183)
test tests::benchmark_string_is_foreign_key                     ... bench:         244 ns/iter (+/- 113)
test tests::benchmark_string_is_kebab                           ... bench:         194 ns/iter (+/- 113)
test tests::benchmark_string_is_screaming_snake                 ... bench:         194 ns/iter (+/- 30)
test tests::benchmark_string_is_sentence                        ... bench:         157 ns/iter (+/- 34)
test tests::benchmark_string_is_snake                           ... bench:         171 ns/iter (+/- 46)
test tests::benchmark_string_is_table                           ... bench:       2,944 ns/iter (+/- 91)
test tests::benchmark_string_is_title                           ... bench:         157 ns/iter (+/- 90)
test tests::benchmark_string_is_train                           ... bench:         165 ns/iter (+/- 87)
test tests::benchmark_string_ordinalize                         ... bench:         155 ns/iter (+/- 58)
test tests::benchmark_string_pluralize                          ... bench:       2,317 ns/iter (+/- 1,330)
test tests::benchmark_string_singular                           ... bench:       2,719 ns/iter (+/- 17)
test tests::benchmark_string_to_camel                           ... bench:         142 ns/iter (+/- 46)
test tests::benchmark_string_to_class                           ... bench:       2,376 ns/iter (+/- 486)
test tests::benchmark_string_to_foreign_key                     ... bench:         455 ns/iter (+/- 88)
test tests::benchmark_string_to_kebab                           ... bench:         163 ns/iter (+/- 48)
test tests::benchmark_string_to_screaming_snake                 ... bench:         185 ns/iter (+/- 78)
test tests::benchmark_string_to_sentence                        ... bench:         147 ns/iter (+/- 4)
test tests::benchmark_string_to_snake                           ... bench:         165 ns/iter (+/- 23)
test tests::benchmark_string_to_table                           ... bench:       2,489 ns/iter (+/- 833)
test tests::benchmark_string_to_title                           ... bench:         147 ns/iter (+/- 41)
test tests::benchmark_string_to_train                           ... bench:         158 ns/iter (+/- 73)
```

### CODE REVIEW

**Comment by whatisinternet** [comment]
Comparison with current [master](https://github.com/whatisinternet/inflector/commit/cc8ffa254632df1858b25dc0cb64c7a43b758228):
```shell
 name                                                        benches-control ns/iter  benches-variable ns/iter  diff ns/iter   diff % 
 cases::camelcase::tests::bench_camel0                       161                      132                                -29  -18.01% 
 cases::camelcase::tests::bench_camel1                       160                      135                                -25  -15.62% 
 cases::camelcase::tests::bench_camel2                       158                      132                                -26  -16.46% 
 cases::camelcase::tests::bench_is_camel                     173                      145                                -28  -16.18% 
 cases::kebabcase::tests::bench_is_kebab                     217                      170                                -47  -21.66% 
 cases::kebabcase::tests::bench_kebab                        191                      173                                -18   -9.42% 
 cases::pascalcase::tests::bench_is_pascal                   181                      150                                -31  -17.13% 
 2mcases::pascalcase::tests::bench_pascal0                     175                      142                                -33  -18.86% 
 cases::pascalcase::tests::bench_pascal1                     170                      143                                -27  -15.88% 
 cases::pascalcase::tests::bench_pascal2                     169                      141                                -28  -16.57% 
 cases::screamingsnakecase::tests::bench_is_screaming_snake  227                      181                                -46  -20.26% 
 cases::screamingsnakecase::tests::bench_screaming_snake     198                      179                                -19   -9.60% 
 cases::sentencecase::tests::bench_is_sentence               202                      160                                -42  -20.79% 
 cases::sentencecase::tests::bench_sentence                  233                      204                                -29  -12.45% 
 cases::sentencecase::tests::bench_sentence_from_snake       176                      150                                -26  -14.77% 
 cases::snakecase::tests::bench_is_snake                     225                      170                                -55  -24.44% 
 cases::snakecase::tests::bench_snake_from_camel             186                      163                                -23  -12.37% 
 cases::snakecase::tests::bench_snake_from_title             191                      173                                -18   -9.42% 
 cases::titlecase::tests::bench_is_title                     208                      159                                -49  -23.56% 
 cases::titlecase::tests::bench_title                        232                      204                                -28  -12.07% 
 cases::titlecase::tests::bench_title_from_snake             177                      149                                -28  -15.82% 
 cases::traincase::tests::bench_is_train                     206                      157                                -49  -23.79% 
 cases::traincase::tests::bench_train                        177                      150                                -27  -15.25% 
 cases::traincase::tests::bench_train_from_snake             284                      243                                -41  -14.44% 
 tests::benchmark_str_deordinalize                           160                      127                                -33  -20.62% 
 tests::benchmark_str_is_camel                               188                      139                                -49  -26.06% 
 tests::benchmark_str_is_foreign_key                         255                      236                                -19   -7.45% 
 tests::benchmark_str_is_kebab                               219                      170                                -49  -22.37% 
 tests::benchmark_str_is_screaming_snake                     232                      180                                -52  -22.41% 
 tests::benchmark_str_is_sentence                            204                      165                                -39  -19.12% 
 tests::benchmark_str_is_snake                               218                      172                                -46  -21.10% 
 tests::benchmark_str_is_title                               205                      180                                -25  -12.20% 
 tests::benchmark_str_is_train                               206                      180                                -26  -12.62% 
 tests::benchmark_str_ordinalize                             205                      132                                -73  -35.61% 
 tests::benchmark_str_to_camel                               160                      134                                -26  -16.25% 
 tests::benchmark_str_to_foreign_key                         482                      416                                -66  -13.69% 
 tests::benchmark_str_to_kebab                               182                      153                                -29  -15.93% 
 tests::benchmark_str_to_sentence                            176                      148                                -28  -15.91% 
 tests::benchmark_str_to_snake                               184                      155                                -29  -15.76% 
 tests::benchmark_str_to_title                               176                      148                                -28  -15.91% 
 tests::benchmark_str_to_train                               176                      148                                -28  -15.91% 
 tests::benchmark_string_deordinalize                        183                      153                                -30  -16.39% 
 tests::benchmark_string_is_camel                            202                      149                                -53  -26.24% 
 tests::benchmark_string_is_foreign_key                      289                      252                                -37  -12.80% 
 tests::benchmark_string_is_kebab                            253                      192                                -61  -24.11% 
 tests::benchmark_string_is_screaming_snake                  263                      201                                -62  -23.57% 
 tests::benchmark_string_is_sentence                         217                      188                                -29  -13.36% 
 tests::benchmark_string_is_snake                            252                      193                                -59  -23.41% 
 tests::benchmark_string_is_title                            211                      167                                -44  -20.85% 
 tests::benchmark_string_is_train                            210                      187                                -23  -10.95% 
 tests::benchmark_string_ordinalize                          234                      161                                -73  -31.20% 
 tests::benchmark_string_to_camel                            173                      143                                -30  -17.34% 
 tests::benchmark_string_to_foreign_key                      495                      457                                -38   -7.68% 
 tests::benchmark_string_to_kebab                            210                      189                                -21  -10.00% 
 tests::benchmark_string_to_screaming_snake                  235                      218                                -17   -7.23% 
 tests::benchmark_string_to_sentence                         186                      159                                -27  -14.52% 
 tests::benchmark_string_to_snake                            210                      184                                -26  -12.38% 
 tests::benchmark_string_to_title                            185                      159                                -26  -14.05% 
 tests::benchmark_string_to_train                            185                      160                                -25  -13.51% 
```

**Comment by RReverser** [comment]
Thanks!
Nitpick: looks like the second table is missing `*_class` benchmarks?

**Comment by whatisinternet** [comment]
No problem, it was a good idea. 

WRT the second table: I only displayed conversions that exceeded a delta greater than 10%. I can generate the full report if you'd like. Or you can do it yourself using [cargo benchcmp]( https://github.com/BurntSushi/cargo-benchcmp) with the following (on nightly rust):


```shell
#!/bin/sh

cargo bench --features=unstable>variable &&\
git checkout cc8ffa2 && \
cargo bench --features=unstable>control &&\
cargo benchcmp control variable &&\
git checkout master
```

**Comment by RReverser** [comment]
Ah right, fair enough - didn't notice it was already benchcmp report and not just output from second `cargo bench`.

**Pull request merged**
